# Generated by Django 5.2.4 on 2025-08-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='sub_category/'),
        ),
    ]
