# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
